use_frameworks!

target 'FyreSwiftExtensions_Example' do
  pod 'FyreSwiftExtensions', :path => '../'
  pod 'NVActivityIndicatorView'

  target 'FyreSwiftExtensions_Tests' do
    inherit! :search_paths

    
  end
end
